print("++++++ DATA DIRI MAHASISWA ++++++")
NIM = input("NIM : ")
Nama = input("Nama : ")
Jurusan = input("Jurusan : ")
Alamat = input("Alamat : ")
print("")
print("++++++ HASIL CETAK DIATAS ADALAH ++++++")
print("NIM      : " +str(NIM))
print("Nama     : " +str(Nama))
print("Jurusan  : " +str(Jurusan))
print("Alamat   : " +str(Alamat))
